---
kind: pipeline
type: docker
name: default

services:
  - name: etcd
    image: gcr.io/etcd-development/etcd:v3.4.0
    commands:
      - |
        /usr/local/bin/etcd \
        --name s1 \
        --listen-client-urls http://0.0.0.0:2379 \
        --advertise-client-urls http://0.0.0.0:2379 \
        --listen-peer-urls http://0.0.0.0:2380 \
        --initial-advertise-peer-urls http://0.0.0.0:2380 \
        --initial-cluster s1=http://0.0.0.0:2380 \
        --initial-cluster-token tkn \
        --initial-cluster-state new \
        --log-level debug \
        --logger zap \
        --log-outputs stderr

steps:
  - name: unit-and-integration
    image: golang:1.13.0
    commands:
      - sleep 5
      - make integration-verbose
